force-app/main/default/objects/Integration_Event__e/Integration_Event__e.object-meta.xml
<CustomObject>
    <description>Real-time tracking + monitoring layer</description>
    <label>Integration Event</label>
    <pluralLabel>Integration Events</pluralLabel>
</CustomObject>

force-app/main/default/objects/Integration_Event__e/fields/Event_Type__c.field-meta.xml
<CustomField>
    <fullName>Event_Type__c</fullName>
    <label>Event Type</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Event__e/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Human readable status</description>
    <label>Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Event__e/fields/Order_Id__c.field-meta.xml
<CustomField>
    <fullName>Order_Id__c</fullName>
    <description>Reference to Integration_Order__c</description>
    <label>Order Id</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Event__e/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>Event time</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PlatformEventPublisher.cls
public with sharing class PlatformEventPublisher {

    public static void publishEvent(
        String eventType,
        Id orderId,
        String message
    ) {
        Integration_Event__e eventRecord = new Integration_Event__e();
        eventRecord.Event_Type__c = eventType;
        eventRecord.Order_Id__c =String.valueOf(orderId);
        eventRecord.Message__c = message;
        eventRecord.Timestamp__c = System.now();

        Database.SaveResult result =EventBus.publish(eventRecord);
        if (!result.isSuccess()) {
            System.debug('Platform Event publish failed');
        }
    }
}