force-app/main/default/objects/Integration_Order__c/Integration_Order__c.object-meta.xml
<CustomObject>
    <label>Integration Order</label>
    <nameField>
        <displayFormat>IO-{0000}</displayFormat>
        <label>Integration Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Order__c/fields/Last_Error__c.field-meta.xml
<CustomField>
    <fullName>Last_Error__c</fullName>
    <inlineHelpText>Last failure reason</inlineHelpText>
    <label>Error Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Order__c/fields/Order_Number__c.field-meta.xml
<CustomField>
    <fullName>Order_Number__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>Business order reference</inlineHelpText>
    <label>Order Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Integration_Order__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <inlineHelpText>JSON sent to external system</inlineHelpText>
    <label>Payload</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Order__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <inlineHelpText>API response stored</inlineHelpText>
    <label>Response</label>
    <length>130000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Order__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <inlineHelpText>Tracks retry attempts</inlineHelpText>
    <label>Retry Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Integration_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Failed</fullName>
                <default>true</default>
                <label>Failed</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Retrying</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderSyncQueueable.cls
public with sharing class OrderSyncQueueable 
    implements Queueable, Database.AllowsCallouts {

    private Id integrationOrderId;
    private String payload;

    public OrderSyncQueueable(Id integrationOrderId , String payload) {
        this.integrationOrderId = integrationOrderId;
        this.payload = payload;
    }
    public void execute(QueueableContext context) {
        Integration_Order__c orderRec = [SELECT Id,Name,Order_Number__c,Status__c,Payload__c,Retry_Count__c,Response__c,Last_Error__c FROM Integration_Order__c WHERE Id = :integrationOrderId LIMIT 1];
        try {
            HttpResponse response = ERPCalloutService.sendOrder(orderRec);
            
            Integer statusCode = response.getStatusCode();
            if (statusCode == 200 || statusCode == 201) {
                orderRec.Status__c = 'Success';
                orderRec.Response__c = response.getBody();
                orderRec.Payload__c = JSON.serialize(payload);
                orderRec.Last_Error__c = null;
                update orderRec;

                PlatformEventPublisher.publishEvent(
                    'SUCCESS',
                    orderRec.Id,
                    'Order synced successfully'
                );
            } else {
                handleFailure(
                    orderRec,
                    'HTTP Error: ' + statusCode
                );
            }

        } catch (Exception ex) {
            handleFailure(orderRec,ex.getMessage());
        }
    }
    private void handleFailure(Integration_Order__c orderRec,String errorMessage) {

        Integer retryCount =
            Integer.valueOf(orderRec.Retry_Count__c);
        retryCount++;

        orderRec.Retry_Count__c = retryCount;
        orderRec.Last_Error__c = errorMessage;

        if (retryCount < 3) {

            orderRec.Status__c = 'Retrying';
            update orderRec;

            PlatformEventPublisher.publishEvent(
                'RETRY',
                orderRec.Id,
                'Retry attempt #' + retryCount
            );
            System.enqueueJob(new OrderSyncQueueable(orderRec.Id, orderRec.Payload__c));
        } else {
            orderRec.Status__c = 'Failed';
            update orderRec;

            PlatformEventPublisher.publishEvent(
                'FAILURE',
                orderRec.Id,
                errorMessage
            );
        }
    }
}